# Generated by Django 5.1.6 on 2025-02-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='users_image/')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('rol', models.CharField(choices=[('pr', 'Преподаватель'), ('st', 'Студент'), ('ad', 'Администратор')], max_length=25)),
                ('password', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('ac', 'Активный'), ('in', 'Неактивный')], max_length=25)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
