# Generated by Django 5.1.6 on 2025-02-14 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('desc', models.TextField()),
                ('start_date', models.DateField()),
                ('duration', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('ac', 'Активный'), ('in', 'Неактивный')], max_length=25)),
                ('teacher', models.ForeignKey(limit_choices_to={'rol': 'pr'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='users.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
