# Generated by Django 5.1.6 on 2025-02-14 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('end_date', models.DateField()),
                ('max_score', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('ac', 'Активный'), ('in', 'Неактивный')], max_length=25)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.course')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
